services:
  db_test:
    container_name: ${DB_TEST_CONTAINER_NAME:-db_test}
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-aggregator_db}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER:-postgres}"]
      interval: ${DB_HEALTHCHECK_INTERVAL:-10s}
      timeout: ${DB_HEALTHCHECK_TIMEOUT:-5s}
      retries: ${DB_HEALTHCHECK_RETRIES:-5}

  aggregator_app_test:
    container_name: ${APP_TEST_CONTAINER_NAME:-aggregator_app_test}
    build:
      context: .
      target: test
    environment:
      POSTGRES_USERNAME: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DATABASE_NAME: ${DB_NAME:-aggregator_db}
      POSTGRES_HOST: ${DB_TEST_CONTAINER_NAME:-db_test}
      POSTGRES_PORT: 5432
      LMS_API_KEY: ${LMS_API_KEY:?}
      EVENTS_PROVIDER_BASE_URL: ${EVENTS_PROVIDER_BASE_URL:?}
      CAPASHINO_BASE_URL: ${CAPASHINO_BASE_URL:?}
      OUTBOX_SECONDS_INTERVAL: ${OUTBOX_SECONDS_INTERVAL:-3600}
      INBOX_SECONDS_TTL: ${INBOX_SECONDS_TTL:-3600}
    depends_on:
      db_test:
        condition: service_healthy
