"""add_other_event_status

Revision ID: 1e5544a62bc7
Revises: 6feb905485a6
Create Date: 2026-02-22 08:11:22.272156

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1e5544a62bc7"
down_revision: str | Sequence[str] | None = "6feb905485a6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


old_options = ("NEW", "PUBLISHED")
new_options = old_options + ("OTHER",)

old_type = sa.Enum(*old_options, name="eventstatus")
new_type = sa.Enum(*new_options, name="eventstatus")
tmp_type = sa.Enum(*new_options, name="_eventstatus")

tcr = sa.sql.table("events", sa.Column("status", new_type, nullable=False))


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE eventstatus ADD VALUE 'OTHER'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(tcr.update().where(tcr.c.status == "OTHER").values(status="NEW"))
    tmp_type.create(op.get_bind(), checkfirst=False)
    op.execute(
        "ALTER TABLE events ALTER COLUMN status TYPE _eventstatus"
        " USING status::text::_eventstatus"
    )
    new_type.drop(op.get_bind(), checkfirst=False)
    old_type.create(op.get_bind(), checkfirst=False)
    op.execute(
        "ALTER TABLE events ALTER COLUMN status TYPE eventstatus"
        " USING status::text::eventstatus"
    )
    tmp_type.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
