"""add_outbox_model

Revision ID: 6feb905485a6
Revises: 8a9b422d49b9
Create Date: 2026-02-21 18:35:13.844465

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6feb905485a6"
down_revision: str | Sequence[str] | None = "8a9b422d49b9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outbox",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "type",
            sa.Enum("TICKET_REGISTER", name="outboxtype"),
            nullable=False,
        ),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("WAITING", "SENT", name="outboxstatus"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default="NOW()",
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_outbox_status"), "outbox", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_outbox_status"), table_name="outbox")
    op.drop_table("outbox")
    op.execute("DROP TYPE outboxtype")
    op.execute("DROP TYPE outboxstatus")
    # ### end Alembic commands ###
