"""fix_member_ticket_id

Revision ID: ba993bcb5b90
Revises: fe8d3a6f6f98
Create Date: 2026-02-11 20:17:09.309227

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ba993bcb5b90"
down_revision: str | Sequence[str] | None = "fe8d3a6f6f98"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("members", "ticker_id", new_column_name="ticket_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("members", "ticket_id", new_column_name="ticker_id")
    # ### end Alembic commands ###
