"""add_sync_meta_model

Revision ID: fe8d3a6f6f98
Revises: a3770f47d15d
Create Date: 2026-02-09 11:23:45.233280

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fe8d3a6f6f98"
down_revision: str | Sequence[str] | None = "a3770f47d15d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sync_meta",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("last_sync_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_changed_at", sa.Date(), nullable=True),
        sa.Column(
            "sync_status",
            sa.Enum("NEVER", "PENDING", "SYNCED", name="syncstatus"),
            nullable=False,
        ),
        sa.CheckConstraint("id = 1", name="ck_sync_meta_singleton"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sync_meta")
    op.execute("DROP TYPE syncstatus")
    # ### end Alembic commands ###
